# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3497f796558f1b202196d8fc4a0580dae6aa4ec7e05414379fee65bfcc0796449194d2ac5f8b7cc2f52846f094402e909faab5e158407ec60b1f564e18c0a0f3

test:
  secret_key_base: 9edd488be6fac1b55609ab70f20865cfe19ae90e09e10017c6d71efc8a3e1cfb5a0b774d5afffe56422eda87c24467d465ffde39f3018872b297a9746fd5a350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
